name: Build

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js 24
              uses: actions/setup-node@v5
              with:
                  node-version: "24"
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
            - name: Lint
              run: pnpm run lint
            - name: Test
              run: pnpm run test
