name: Deploy Beta

on: workflow_dispatch

permissions:
    id-token: write
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js 24
              uses: actions/setup-node@v5
              with:
                  node-version: "24"
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
            - name: Publish
              run: |
                  git config --global user.name 'BaklavaJS CICD'
                  git config --global user.email 'newcat@users.noreply.github.com'
                  echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
                  lerna version prerelease --preid beta --yes
                  lerna publish from-package --dist-tag next --yes
            - name: Build docs
              run: |
                  pnpm run generate-api-docs
                  pnpm run docs:build
