name: Publish

permissions:
    id-token: write
    contents: write
    pages: write

on:
    push:
        tags:
            - "**"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js 24
              uses: actions/setup-node@v5
              with:
                  node-version: "24"
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
            - name: Publish
              run: |
                  echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
                  lerna publish from-git --yes
            - name: Build docs
              run: |
                  pnpm run generate-api-docs
                  pnpm run docs:build
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: "./docs/.vitepress/dist/"
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
